// GROVE_FLEET — financed espresso machines
window.GROVE_FLEET = [
  {
    id: 'GRV-ESP-0001',
    type: 'Traditional Espresso',
    make: 'La Marzocco',
    model: 'Linea PB',
    year: 2021,
    hours: 4280,
    originalCost: 18900,
    loanBalance: 9625,
    originAdvance: 15120,
    borrower: 'North Loop Coffee Roasters',
    location: 'Austin, TX',
    lender: 'Grove Asset Credit',
    serial: 'LMPB3AV-21-77341',
    vin: null,
    image: '',
    configuration: '3-group AV',
    groupHeads: 3,
    conditionRating: 'good',
    riskFlags: ['service-due-30d'],
    dataSource: 'verified',
  },
  {
    id: 'GRV-ESP-0002',
    type: 'Specialty Modulating',
    make: 'Slayer',
    model: 'Steam LP',
    year: 2022,
    hours: 3190,
    originalCost: 24500,
    loanBalance: 15680,
    originAdvance: 19600,
    borrower: 'Pine & Porter Café',
    location: 'Portland, OR',
    lender: 'Grove Asset Credit',
    serial: 'SLY-STLP2-22-11409',
    vin: null,
    image: '',
    configuration: '2-group',
    groupHeads: 2,
    conditionRating: 'excellent',
    riskFlags: [],
    dataSource: 'verified',
  },
  {
    id: 'GRV-ESP-0003',
    type: 'Specialty Modulating',
    make: 'Synesso',
    model: 'MVP Hydra',
    year: 2020,
    hours: 6110,
    originalCost: 31200,
    loanBalance: 19840,
    originAdvance: 24960,
    borrower: 'Harborline Espresso Bar',
    location: 'Seattle, WA',
    lender: 'Grove Asset Credit',
    serial: 'SNS-MVPH3-20-55218',
    vin: null,
    image: '',
    configuration: '3-group',
    groupHeads: 3,
    conditionRating: 'fair',
    riskFlags: ['ltv-watch', 'high-usage'],
    dataSource: 'verified',
  },
  {
    id: 'GRV-ESP-0004',
    type: 'Traditional Espresso',
    make: 'Victoria Arduino',
    model: 'Black Eagle',
    year: 2023,
    hours: 1760,
    originalCost: 19750,
    loanBalance: 13840,
    originAdvance: 15800,
    borrower: 'Canal Street Coffeehouse',
    location: 'New Orleans, LA',
    lender: 'Grove Asset Credit',
    serial: 'VA-BE2VA-23-33872',
    vin: null,
    image: '',
    configuration: '2-group VA',
    groupHeads: 2,
    conditionRating: 'excellent',
    riskFlags: [],
    dataSource: 'verified',
  },
  {
    id: 'GRV-ESP-0005',
    type: 'Traditional Espresso',
    make: 'Nuova Simonelli',
    model: 'Aurelia Wave',
    year: 2021,
    hours: 4875,
    originalCost: 14200,
    loanBalance: 8440,
    originAdvance: 11360,
    borrower: 'Brickline Café & Bakery',
    location: 'Chicago, IL',
    lender: 'Grove Asset Credit',
    serial: 'NS-AW2-21-94016',
    vin: null,
    image: '',
    configuration: '2-group',
    groupHeads: 2,
    conditionRating: 'good',
    riskFlags: ['water-filtration-check'],
    dataSource: 'verified',
  },
];

// GROVE_COMPS — sale/auction transactions
window.GROVE_COMPS = [];
