// GROVE_BRAND_LOGOS — maps brand names to manufacturer domains for logo.dev
// Usage: <img src={`https://img.logo.dev/${GROVE_BRAND_LOGOS[brand]}?token=pk_free&size=60`} />
window.GROVE_BRAND_LOGOS = {
  "Ascaso": "ascaso.com",
  "Astoria": "astoria.com",
  "BFC/Royal": "bfroyalfirst.it",
  "Bezzera": "bfroyalfirst.it",
  "Breville": "breville.com",
  "Carimali": "carimali.com",
  "Casadio": "casadio.com",
  "Conti": "conti-espresso.com",
  "Dalla Corte": "dallacorte.com",
  "Decent Espresso": "decentespresso.com",
  "ECM": "ecm.de",
  "Elektra": "elektrasrl.com",
  "Estella Caffe": "webstaurantstore.com",
  "Eversys": "eversys.com",
  "Expobar": "cfrancis.com",
  "Faema": "faema.com",
  "Fiamma": "fiammaespresso.com",
  "Fracino": "fracino.com",
  "Franke": "franke.com",
  "Gaggia": "gaggia.com",
  "Iberital": "iberital.com",
  "Jura Professional": "jura.com",
  "Kees van der Westen": "kfroyalfirst.it",
  "LUCCA": "prima-coffee.com",
  "La Cimbali": "cimbali.com",
  "La Marzocco": "lamarzocco.com",
  "La San Marco": "lasanmarco.com",
  "La Spaziale": "laspaziale.com",
  "Lelit": "lelit.com",
  "MAVAM": "mavamespresso.com",
  "Magister": "magister-es.com",
  "Melitta": "melitta.com",
  "Melitta/Cafina": "melitta.com",
  "Modbar": "modbar.com",
  "Necta": "evocagroup.com",
  "Necta/Evoca": "evocagroup.com",
  "Nuova Simonelli": "nuovasimonelli.com",
  "Orchestrale": "orchestrale.com",
  "Profitec": "profitec-espresso.com",
  "Promac": "promac-espresso.it",
  "Rancilio": "ranciliogroup.com",
  "Reneka": "reneka.com",
  "Rocket": "rocket-espresso.com",
  "Sanremo": "sanremomachines.com",
  "Schaerer": "schaerer.com",
  "Slayer": "slayerespresso.com",
  "Synesso": "synesso.com",
  "Thermoplan": "thermoplan.ch",
  "Unic": "unic-espresso.com",
  "Victoria Arduino": "victoriaarduino.com",
  "WMF": "wmf.com",
  "Wega": "wega.it"
};
